apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: cpu-stress-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-stress-test
  template:
    metadata:
      labels:
        app: cpu-stress-test
    spec:
      containers:
      - name: stress
        image: progrium/stress
        args:
        - --cpu
        - "4"  # Number of CPU cores to stress, adjust as needed