apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800" # Keeps the container alive for 1 week
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always